name: lubilu
favicon: null
layout_spectrum: 0.15669
typography_spectrum: 0.26743
title: FUNCTIONAL FASHION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#c4daea'
    - '#464646'
    - '#ffffff'
    - '#797f86'
  brandStrength: 0.2840019667055458
  lightness: 0.5613167632836848
  saturation: 0.4940922304522246
  rhythmicContrast: 0.40943798748776317
purpose: []
